source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.1'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]

  # Testing tools
  gem 'rspec'

  #  Debugging tools
  gem 'pry'
  gem 'pry-byebug'

  # Linting
  gem 'rubocop'
  gem 'rubocop-rspec'
end

